# -*- coding: utf-8 -*-
"""amazon_sales_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WEmRUuVilC3ehceQBbcI78efxnWvRxsp
"""

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

path = '/content/drive/MyDrive/Colab Notebooks/FinalProjectLV1/Amazon Sale Report.csv'
df = pd.read_csv(path, low_memory=False)

print("--- 5 Dòng đầu tiên của dữ liệu ---")
display(df.head())

# LÀM SẠCH DỮ LIỆU (DATA CLEANING)
# Xóa các cột không cần thiết
cols_to_drop = ['index', 'Unnamed: 22', 'currency', 'ship-country', 'Sales Channel ']
df.drop(columns=cols_to_drop, inplace=True, errors='ignore')
# Xóa các dòng không có số tiền (Amount) vì không thể tính toán doanh thu
df.dropna(subset=['Amount'], inplace=True)
# Thay thế các giá trị trống ở cột Courier Status bằng 'Unknown' để không bị mất dữ liệu dòng đó
df['Courier Status'].fillna('Unknown', inplace=True)
# Chuyển đổi định dạng ngày tháng (Data Type Conversion)
df['Date'] = pd.to_datetime(df['Date'])
# Kiểm tra lại dữ liệu sau khi lọc
print("--- LÀM SẠCH THÀNH CÔNG ---")
print(f"Số dòng còn lại: {df.shape[0]}")
print(f"Số cột còn lại: {df.shape[1]}")
print("\nCác loại dữ liệu hiện tại:")
print(df.dtypes)

df.to_csv('Amazon_Sale_Report_Cleaned.csv', index=False)
from google.colab import files
files.download('Amazon_Sale_Report_Cleaned.csv')
print("Đang chuẩn bị tải file")